# Generated by Django 4.0.5 on 2022-06-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
